#include <stdint.h>

/* Type definitions generated by 'types.pl' */
typedef char               mp_sign;
typedef uint16_t     mp_digit;  /* 2 byte type */
typedef uint32_t       mp_word;   /* 4 byte type */
typedef unsigned int       mp_size;
typedef int                mp_err;

#define MP_DIGIT_BIT       (CHAR_BIT*sizeof(mp_digit))
#define MP_DIGIT_MAX       USHRT_MAX
#define MP_WORD_BIT        (CHAR_BIT*sizeof(mp_word))
#define MP_WORD_MAX        ULONG_MAX

#define MP_DIGIT_SIZE      2
#define DIGIT_FMT          "%04X"
#define RADIX              ((uint32_t)MP_DIGIT_MAX+1)


/* $Source$ */
/* $Revision$ */
/* $Date$ */
